[build]
builder = "nixpacks"
buildCommand = "pip install poetry && poetry install --no-root"

[deploy]
startCommand = "python3 api.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
